# Generated by Django 4.1.6 on 2023-02-13 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('string', models.CharField(max_length=255, unique=True, verbose_name='Оригинальная строка')),
                ('answers', models.IntegerField(default=0, verbose_name='Сумма ответов')),
            ],
            options={
                'verbose_name': 'Оригинал строки',
                'verbose_name_plural': 'Оригиналы строк',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='UserID')),
                ('age', models.IntegerField(blank=True, verbose_name='Возраст пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file', models.FileField(upload_to='audio/<django.db.models.query_utils.DeferredAttribute object at 0x0000023CE79EE6E0>', verbose_name='Аудио')),
                ('original_string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='backend.originalstring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='backend.telegramuser')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
