# Generated by Django 4.1.6 on 2023-02-13 05:45

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='file',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='sounds'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='original_string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.originalstring'),
        ),
    ]
