# Generated by Django 4.1.6 on 2023-02-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_useranswers_file_useranswers_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='audio_file',
            field=models.FileField(upload_to='sounds', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='original_string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='backend.originalstring'),
        ),
    ]
