# Generated by Django 4.1.6 on 2023-02-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_useranswers_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('original_string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_batch', to='backend.originalstring')),
            ],
            options={
                'verbose_name': 'Оригинал строки',
                'verbose_name_plural': 'Оригиналы строк',
            },
        ),
    ]
