# Generated by Django 4.1.6 on 2023-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_firstbatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstbatch',
            options={'verbose_name': 'Первоочередный набор'},
        ),
        migrations.AddField(
            model_name='useranswers',
            name='audio_len',
            field=models.FloatField(blank=True, default=0, verbose_name='Длительность аудио'),
            preserve_default=False,
        ),
    ]
